name: Continuous Integration2
on: push

jobs:
  unit-test:
    name: Unit Test2
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node: [16, 18]
      fail-fast: false
      max-parallel: 4
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set Node.js ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
      - name: Get NPM cache directory
        id: npm-cache
        run: |
          echo "::set-output name=dir::$(npm config get cache)"
      - name: Cache NPM
        uses: actions/cache@v3
        with:
          path: ${{ steps.npm-cache.outputs.dir}}
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json')}}
          restore-keys: |
            ${{ runner.os}}-node-${{ matrix.node}}
      - name: Install dependencies
        run: npm ci
      - name: Test
        run: npm test
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Chcekout
        uses: actions/checkout@v4
      - name: Set Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Get NPM cache directory
        id: npm-cache
        run: |
          echo "::set-output name=dir::$(npm config get cache)"
      - name: Cache NPM
        uses: actions/cache@v3
        with:
          path: ${{ steps.npm-cache.outputs.dir}}
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json')}}
          restore-keys: |
            ${{ runner.os}}-node--lint
            - name: Install dependencies
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npm run lint
