name: Secrutiy Audit
on:
  schedule:
    - cron: "0 0 * * *"
  push:

jobs:
  audit:
    name: Security Audit
    permissions:
      contents: write
      packages: write
      statuses: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: Install dependencies
        run: npm ci
      - name: Audit
        id: npm_audit
        run: npm audit
        continue-on-error: true

      - name: Fix
        id: npm_audit_fix
        run: npm audit fix
        if: steps.npm_audit.outcome == 'failure'

      - name: commit & push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add -A .
          git commit -m "npm audit fix" || echo "No changes to commit"
          git push
        if: steps.npm_audit_fix.outcome == 'success'
