name: Secrutiy Audit
on:
  schedule:
    - cron: "0 0 * * *"
  push:

jobs:
  audit:
    name: Security Audit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: Install dependencies
        run: npm ci
      - name: Audit
        id: npm_audit
        run: npm audit
        continue-on-error: true

      - name: Fix
        run: npm audit fix
        if: steps.npm_audit.outcome == 'failure'
